/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_AJOUTER (void)
{
  GtkWidget *AJOUTER;
  GtkWidget *notebook2;
  GtkWidget *fixed7;
  GtkWidget *fixed8;
  GtkWidget *entry_id;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkObject *spinbutton_jours_adj;
  GtkWidget *spinbutton_jours;
  GtkObject *spinbutton_mois_adj;
  GtkWidget *spinbutton_mois;
  GtkObject *spinbutton_annee_adj;
  GtkWidget *spinbutton_annee;
  GtkWidget *entry_telephone;
  GtkWidget *entry_mail;
  GtkObject *spinbutton_salaire_adj;
  GtkWidget *spinbutton_salaire;
  GtkWidget *entry_cin;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkWidget *label80;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkWidget *label84;
  GtkWidget *comboboxentry_gouvernorat;
  GtkWidget *comboboxentry_idpark;
  GtkWidget *label71;
  GtkWidget *checkbutton_maintenence;
  GtkWidget *checkbutton_securite;
  GtkWidget *checkbutton_agent;
  GtkWidget *radiobutton_femme;
  GSList *radiobutton_femme_group = NULL;
  GtkWidget *button_retour;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label149;
  GtkWidget *button_ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label72;
  GtkWidget *radiobutton_homme;
  GtkWidget *label66;
  GtkWidget *empty_notebook_page;
  GtkWidget *label70;

  AJOUTER = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AJOUTER), _("ajouter"));

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (AJOUTER), notebook2);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed7);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 0, 0);
  gtk_widget_set_size_request (fixed8, 672, 808);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_id, 112, 64);
  gtk_widget_set_size_request (entry_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_nom, 112, 120);
  gtk_widget_set_size_request (entry_nom, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_prenom, 112, 168);
  gtk_widget_set_size_request (entry_prenom, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  spinbutton_jours_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 0);
  spinbutton_jours = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jours_adj), 1, 0);
  gtk_widget_show (spinbutton_jours);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_jours, 208, 360);
  gtk_widget_set_size_request (spinbutton_jours, 60, 27);

  spinbutton_mois_adj = gtk_adjustment_new (0, 1, 12, 1, 10, 0);
  spinbutton_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_adj), 1, 0);
  gtk_widget_show (spinbutton_mois);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_mois, 328, 360);
  gtk_widget_set_size_request (spinbutton_mois, 60, 27);

  spinbutton_annee_adj = gtk_adjustment_new (0, 1900, 2025, 1, 10, 0);
  spinbutton_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annee_adj), 1, 0);
  gtk_widget_show (spinbutton_annee);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_annee, 464, 360);
  gtk_widget_set_size_request (spinbutton_annee, 60, 27);

  entry_telephone = gtk_entry_new ();
  gtk_widget_show (entry_telephone);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_telephone, 128, 408);
  gtk_widget_set_size_request (entry_telephone, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_telephone), 8226);

  entry_mail = gtk_entry_new ();
  gtk_widget_show (entry_mail);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_mail, 120, 520);
  gtk_widget_set_size_request (entry_mail, 192, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mail), 8226);

  spinbutton_salaire_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 0);
  spinbutton_salaire = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_salaire_adj), 1, 0);
  gtk_widget_show (spinbutton_salaire);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton_salaire, 152, 680);
  gtk_widget_set_size_request (spinbutton_salaire, 144, 32);

  entry_cin = gtk_entry_new ();
  gtk_widget_show (entry_cin);
  gtk_fixed_put (GTK_FIXED (fixed8), entry_cin, 112, 216);
  gtk_widget_set_size_request (entry_cin, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin), 8226);

  label73 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed8), label73, 8, 120);
  gtk_widget_set_size_request (label73, 80, 24);

  label74 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed8), label74, 8, 168);
  gtk_widget_set_size_request (label74, 80, 25);

  label75 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed8), label75, 24, 216);
  gtk_widget_set_size_request (label75, 56, 25);

  label76 = gtk_label_new (_("sexe : "));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed8), label76, 16, 280);
  gtk_widget_set_size_request (label76, 64, 32);

  label77 = gtk_label_new (_("Date de naissance :                                    "));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed8), label77, 0, 360);
  gtk_widget_set_size_request (label77, 136, 32);

  label78 = gtk_label_new (_("Telephone : "));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed8), label78, 0, 408);
  gtk_widget_set_size_request (label78, 112, 40);

  label79 = gtk_label_new (_("Gouvernorat :"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed8), label79, 0, 464);
  gtk_widget_set_size_request (label79, 104, 40);

  label80 = gtk_label_new (_("Mail : "));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed8), label80, 8, 520);
  gtk_widget_set_size_request (label80, 64, 32);

  label81 = gtk_label_new (_("Poste de travail : "));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed8), label81, 0, 568);
  gtk_widget_set_size_request (label81, 144, 48);

  label82 = gtk_label_new (_("ID park : "));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed8), label82, 16, 624);
  gtk_widget_set_size_request (label82, 96, 32);

  label83 = gtk_label_new (_("Salaire :"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed8), label83, 8, 680);
  gtk_widget_set_size_request (label83, 104, 33);

  label84 = gtk_label_new (_("Id :"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed8), label84, 32, 72);
  gtk_widget_set_size_request (label84, 41, 17);

  comboboxentry_gouvernorat = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_gouvernorat);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry_gouvernorat, 120, 472);
  gtk_widget_set_size_request (comboboxentry_gouvernorat, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("B\303\251ja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Ben Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Sidi Bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Gabes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Kebili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("M\303\251denine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("La Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_gouvernorat), _("Mahdia"));

  comboboxentry_idpark = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_idpark);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry_idpark, 152, 624);
  gtk_widget_set_size_request (comboboxentry_idpark, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_idpark), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_idpark), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_idpark), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_idpark), _("4"));

  label71 = gtk_label_new (_("cree compte"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed8), label71, 344, 0);
  gtk_widget_set_size_request (label71, 128, 48);

  checkbutton_maintenence = gtk_check_button_new_with_mnemonic (_("maintenence"));
  gtk_widget_show (checkbutton_maintenence);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton_maintenence, 176, 576);
  gtk_widget_set_size_request (checkbutton_maintenence, 118, 24);

  checkbutton_securite = gtk_check_button_new_with_mnemonic (_("securite"));
  gtk_widget_show (checkbutton_securite);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton_securite, 320, 576);
  gtk_widget_set_size_request (checkbutton_securite, 118, 24);

  checkbutton_agent = gtk_check_button_new_with_mnemonic (_("agent"));
  gtk_widget_show (checkbutton_agent);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton_agent, 448, 576);
  gtk_widget_set_size_request (checkbutton_agent, 118, 24);

  radiobutton_femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_femme);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton_femme, 232, 288);
  gtk_widget_set_size_request (radiobutton_femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme), radiobutton_femme_group);
  radiobutton_femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme));

  button_retour = gtk_button_new ();
  gtk_widget_show (button_retour);
  gtk_fixed_put (GTK_FIXED (fixed8), button_retour, 80, 744);
  gtk_widget_set_size_request (button_retour, 112, 45);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_retour), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label149 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (hbox15), label149, FALSE, FALSE, 0);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed8), button_ajouter, 456, 752);
  gtk_widget_set_size_request (button_ajouter, 112, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox4), label72, FALSE, FALSE, 0);

  radiobutton_homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_homme);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton_homme, 96, 288);
  gtk_widget_set_size_request (radiobutton_homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme), radiobutton_femme_group);
  radiobutton_femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme));

  label66 = gtk_label_new (_("label66"));
  gtk_widget_show (label66);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label66);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook2), empty_notebook_page);

  label70 = gtk_label_new (_("label70"));
  gtk_widget_show (label70);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label70);

  g_signal_connect ((gpointer) checkbutton_maintenence, "toggled",
                    G_CALLBACK (on_checkbutton_maintenence_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_securite, "toggled",
                    G_CALLBACK (on_checkbutton_securite_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_agent, "toggled",
                    G_CALLBACK (on_checkbutton_agent_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_femme, "toggled",
                    G_CALLBACK (on_radiobutton_femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_retour, "clicked",
                    G_CALLBACK (on_button_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_homme, "toggled",
                    G_CALLBACK (on_radiobutton_homme_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AJOUTER, AJOUTER, "AJOUTER");
  GLADE_HOOKUP_OBJECT (AJOUTER, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (AJOUTER, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (AJOUTER, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (AJOUTER, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (AJOUTER, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (AJOUTER, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (AJOUTER, spinbutton_jours, "spinbutton_jours");
  GLADE_HOOKUP_OBJECT (AJOUTER, spinbutton_mois, "spinbutton_mois");
  GLADE_HOOKUP_OBJECT (AJOUTER, spinbutton_annee, "spinbutton_annee");
  GLADE_HOOKUP_OBJECT (AJOUTER, entry_telephone, "entry_telephone");
  GLADE_HOOKUP_OBJECT (AJOUTER, entry_mail, "entry_mail");
  GLADE_HOOKUP_OBJECT (AJOUTER, spinbutton_salaire, "spinbutton_salaire");
  GLADE_HOOKUP_OBJECT (AJOUTER, entry_cin, "entry_cin");
  GLADE_HOOKUP_OBJECT (AJOUTER, label73, "label73");
  GLADE_HOOKUP_OBJECT (AJOUTER, label74, "label74");
  GLADE_HOOKUP_OBJECT (AJOUTER, label75, "label75");
  GLADE_HOOKUP_OBJECT (AJOUTER, label76, "label76");
  GLADE_HOOKUP_OBJECT (AJOUTER, label77, "label77");
  GLADE_HOOKUP_OBJECT (AJOUTER, label78, "label78");
  GLADE_HOOKUP_OBJECT (AJOUTER, label79, "label79");
  GLADE_HOOKUP_OBJECT (AJOUTER, label80, "label80");
  GLADE_HOOKUP_OBJECT (AJOUTER, label81, "label81");
  GLADE_HOOKUP_OBJECT (AJOUTER, label82, "label82");
  GLADE_HOOKUP_OBJECT (AJOUTER, label83, "label83");
  GLADE_HOOKUP_OBJECT (AJOUTER, label84, "label84");
  GLADE_HOOKUP_OBJECT (AJOUTER, comboboxentry_gouvernorat, "comboboxentry_gouvernorat");
  GLADE_HOOKUP_OBJECT (AJOUTER, comboboxentry_idpark, "comboboxentry_idpark");
  GLADE_HOOKUP_OBJECT (AJOUTER, label71, "label71");
  GLADE_HOOKUP_OBJECT (AJOUTER, checkbutton_maintenence, "checkbutton_maintenence");
  GLADE_HOOKUP_OBJECT (AJOUTER, checkbutton_securite, "checkbutton_securite");
  GLADE_HOOKUP_OBJECT (AJOUTER, checkbutton_agent, "checkbutton_agent");
  GLADE_HOOKUP_OBJECT (AJOUTER, radiobutton_femme, "radiobutton_femme");
  GLADE_HOOKUP_OBJECT (AJOUTER, button_retour, "button_retour");
  GLADE_HOOKUP_OBJECT (AJOUTER, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (AJOUTER, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (AJOUTER, image15, "image15");
  GLADE_HOOKUP_OBJECT (AJOUTER, label149, "label149");
  GLADE_HOOKUP_OBJECT (AJOUTER, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (AJOUTER, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (AJOUTER, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (AJOUTER, image4, "image4");
  GLADE_HOOKUP_OBJECT (AJOUTER, label72, "label72");
  GLADE_HOOKUP_OBJECT (AJOUTER, radiobutton_homme, "radiobutton_homme");
  GLADE_HOOKUP_OBJECT (AJOUTER, label66, "label66");
  GLADE_HOOKUP_OBJECT (AJOUTER, label70, "label70");

  return AJOUTER;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed12;
  GtkWidget *entry__rechercher;
  GtkWidget *button__ajouter;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label141;
  GtkWidget *button2__retour__rech;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label150;
  GtkWidget *button___rechercher;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label142;
  GtkWidget *treeview1;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window1), fixed12);
  gtk_widget_set_size_request (fixed12, 753, 683);

  entry__rechercher = gtk_entry_new ();
  gtk_widget_show (entry__rechercher);
  gtk_fixed_put (GTK_FIXED (fixed12), entry__rechercher, 584, 56);
  gtk_widget_set_size_request (entry__rechercher, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry__rechercher), 8226);

  button__ajouter = gtk_button_new ();
  gtk_widget_show (button__ajouter);
  gtk_fixed_put (GTK_FIXED (fixed12), button__ajouter, 608, 744);
  gtk_widget_set_size_request (button__ajouter, 112, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button__ajouter), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label141 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label141);
  gtk_box_pack_start (GTK_BOX (hbox8), label141, FALSE, FALSE, 0);

  button2__retour__rech = gtk_button_new ();
  gtk_widget_show (button2__retour__rech);
  gtk_fixed_put (GTK_FIXED (fixed12), button2__retour__rech, 144, 744);
  gtk_widget_set_size_request (button2__retour__rech, 128, 37);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button2__retour__rech), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label150 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label150);
  gtk_box_pack_start (GTK_BOX (hbox16), label150, FALSE, FALSE, 0);

  button___rechercher = gtk_button_new ();
  gtk_widget_show (button___rechercher);
  gtk_fixed_put (GTK_FIXED (fixed12), button___rechercher, 440, 56);
  gtk_widget_set_size_request (button___rechercher, 122, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button___rechercher), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label142 = gtk_label_new_with_mnemonic (_("Rechercher :"));
  gtk_widget_show (label142);
  gtk_box_pack_start (GTK_BOX (hbox9), label142, FALSE, FALSE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview1, 16, 216);
  gtk_widget_set_size_request (treeview1, 1248, 344);

  g_signal_connect ((gpointer) button__ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2__retour__rech, "clicked",
                    G_CALLBACK (on_button2__retour__rech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button___rechercher, "clicked",
                    G_CALLBACK (on_button___rechercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window1, entry__rechercher, "entry__rechercher");
  GLADE_HOOKUP_OBJECT (window1, button__ajouter, "button__ajouter");
  GLADE_HOOKUP_OBJECT (window1, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label141, "label141");
  GLADE_HOOKUP_OBJECT (window1, button2__retour__rech, "button2__retour__rech");
  GLADE_HOOKUP_OBJECT (window1, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window1, image16, "image16");
  GLADE_HOOKUP_OBJECT (window1, label150, "label150");
  GLADE_HOOKUP_OBJECT (window1, button___rechercher, "button___rechercher");
  GLADE_HOOKUP_OBJECT (window1, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window1, image9, "image9");
  GLADE_HOOKUP_OBJECT (window1, label142, "label142");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");

  return window1;
}

GtkWidget*
create_HOME (void)
{
  GtkWidget *HOME;
  GtkWidget *fixed13;
  GtkWidget *label143_;
  GtkWidget *button__rechercher;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label145;
  GtkWidget *button__modifier;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label146;
  GtkWidget *button__ajouter;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label144;
  GtkWidget *button__affrev;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label148;
  GtkWidget *button__supprimer_;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label147;
  GtkWidget *buttonafficherlaliste_;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label169;

  HOME = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (HOME), _("HOME"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (HOME), fixed13);

  label143_ = gtk_label_new (_("welcome"));
  gtk_widget_show (label143_);
  gtk_fixed_put (GTK_FIXED (fixed13), label143_, 104, 8);
  gtk_widget_set_size_request (label143_, 472, 48);
  gtk_label_set_justify (GTK_LABEL (label143_), GTK_JUSTIFY_CENTER);
  gtk_label_set_angle (GTK_LABEL (label143_), 8);

  button__rechercher = gtk_button_new ();
  gtk_widget_show (button__rechercher);
  gtk_fixed_put (GTK_FIXED (fixed13), button__rechercher, 128, 128);
  gtk_widget_set_size_request (button__rechercher, 152, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button__rechercher), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label145 = gtk_label_new_with_mnemonic (_("RECHERCHER "));
  gtk_widget_show (label145);
  gtk_box_pack_start (GTK_BOX (hbox11), label145, FALSE, FALSE, 0);

  button__modifier = gtk_button_new ();
  gtk_widget_show (button__modifier);
  gtk_fixed_put (GTK_FIXED (fixed13), button__modifier, 128, 192);
  gtk_widget_set_size_request (button__modifier, 152, 45);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button__modifier), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label146 = gtk_label_new_with_mnemonic (_("MODIFIER"));
  gtk_widget_show (label146);
  gtk_box_pack_start (GTK_BOX (hbox12), label146, FALSE, FALSE, 0);

  button__ajouter = gtk_button_new ();
  gtk_widget_show (button__ajouter);
  gtk_fixed_put (GTK_FIXED (fixed13), button__ajouter, 128, 64);
  gtk_widget_set_size_request (button__ajouter, 152, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button__ajouter), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label144 = gtk_label_new_with_mnemonic (_("AJOUTER"));
  gtk_widget_show (label144);
  gtk_box_pack_start (GTK_BOX (hbox10), label144, FALSE, FALSE, 0);

  button__affrev = gtk_button_new ();
  gtk_widget_show (button__affrev);
  gtk_fixed_put (GTK_FIXED (fixed13), button__affrev, 128, 384);
  gtk_widget_set_size_request (button__affrev, 152, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button__affrev), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-orientation-landscape", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label148 = gtk_label_new_with_mnemonic (_("AFFREV"));
  gtk_widget_show (label148);
  gtk_box_pack_start (GTK_BOX (hbox14), label148, FALSE, FALSE, 0);

  button__supprimer_ = gtk_button_new ();
  gtk_widget_show (button__supprimer_);
  gtk_fixed_put (GTK_FIXED (fixed13), button__supprimer_, 128, 256);
  gtk_widget_set_size_request (button__supprimer_, 152, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button__supprimer_), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label147 = gtk_label_new_with_mnemonic (_("SUPPRIMER "));
  gtk_widget_show (label147);
  gtk_box_pack_start (GTK_BOX (hbox13), label147, FALSE, FALSE, 0);

  buttonafficherlaliste_ = gtk_button_new ();
  gtk_widget_show (buttonafficherlaliste_);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonafficherlaliste_, 128, 320);
  gtk_widget_set_size_request (buttonafficherlaliste_, 152, 48);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (buttonafficherlaliste_), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label169 = gtk_label_new_with_mnemonic (_("Listes Des Agents"));
  gtk_widget_show (label169);
  gtk_box_pack_start (GTK_BOX (hbox23), label169, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button__rechercher, "clicked",
                    G_CALLBACK (on_button2__rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button__modifier, "clicked",
                    G_CALLBACK (on_button__modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button__ajouter, "clicked",
                    G_CALLBACK (on_button__ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button__affrev, "clicked",
                    G_CALLBACK (on_button__affrev_clicked),
                    NULL);
  g_signal_connect ((gpointer) button__supprimer_, "clicked",
                    G_CALLBACK (on_button__supprimer__clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficherlaliste_, "clicked",
                    G_CALLBACK (on_buttonafficherlaliste__clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (HOME, HOME, "HOME");
  GLADE_HOOKUP_OBJECT (HOME, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (HOME, label143_, "label143_");
  GLADE_HOOKUP_OBJECT (HOME, button__rechercher, "button__rechercher");
  GLADE_HOOKUP_OBJECT (HOME, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (HOME, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (HOME, image11, "image11");
  GLADE_HOOKUP_OBJECT (HOME, label145, "label145");
  GLADE_HOOKUP_OBJECT (HOME, button__modifier, "button__modifier");
  GLADE_HOOKUP_OBJECT (HOME, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (HOME, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (HOME, image12, "image12");
  GLADE_HOOKUP_OBJECT (HOME, label146, "label146");
  GLADE_HOOKUP_OBJECT (HOME, button__ajouter, "button__ajouter");
  GLADE_HOOKUP_OBJECT (HOME, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (HOME, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (HOME, image10, "image10");
  GLADE_HOOKUP_OBJECT (HOME, label144, "label144");
  GLADE_HOOKUP_OBJECT (HOME, button__affrev, "button__affrev");
  GLADE_HOOKUP_OBJECT (HOME, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (HOME, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (HOME, image14, "image14");
  GLADE_HOOKUP_OBJECT (HOME, label148, "label148");
  GLADE_HOOKUP_OBJECT (HOME, button__supprimer_, "button__supprimer_");
  GLADE_HOOKUP_OBJECT (HOME, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (HOME, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (HOME, image13, "image13");
  GLADE_HOOKUP_OBJECT (HOME, label147, "label147");
  GLADE_HOOKUP_OBJECT (HOME, buttonafficherlaliste_, "buttonafficherlaliste_");
  GLADE_HOOKUP_OBJECT (HOME, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (HOME, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (HOME, image23, "image23");
  GLADE_HOOKUP_OBJECT (HOME, label169, "label169");

  return HOME;
}

GtkWidget*
create_MODIFIER (void)
{
  GtkWidget *MODIFIER;
  GtkWidget *fixed14;
  GtkWidget *fixed15;
  GtkWidget *entry____id;
  GtkWidget *entry____nom;
  GtkWidget *entry____prenom;
  GtkObject *spinbutton____jour_adj;
  GtkWidget *spinbutton____jour;
  GtkObject *spinbutton__mois_adj;
  GtkWidget *spinbutton__mois;
  GtkObject *spinbutton__annee_adj;
  GtkWidget *spinbutton__annee;
  GtkWidget *entry____numtelephone;
  GtkWidget *entry____addmail;
  GtkObject *spinbutton____sal_adj;
  GtkWidget *spinbutton____sal;
  GtkWidget *entry____cin;
  GtkWidget *entry____rechercher;
  GtkWidget *label152;
  GtkWidget *label153;
  GtkWidget *label154;
  GtkWidget *label156;
  GtkWidget *label157;
  GtkWidget *label158;
  GtkWidget *label159;
  GtkWidget *label160;
  GtkWidget *label161;
  GtkWidget *label162;
  GtkWidget *button____RECHERCHER_;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label163;
  GtkWidget *button__MODIFIER_;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label166;
  GtkWidget *button2__retour__mod;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label165;
  GtkWidget *label151;
  GtkWidget *label155;
  GtkWidget *comboboxentry____cov;
  GtkWidget *checkbutton____maintenence;
  GtkWidget *checkbutton____securite;
  GtkWidget *checkbutton____agent;
  GtkWidget *comboboxentry____park;
  GtkWidget *radiobutton_____homme;
  GSList *radiobutton_____homme_group = NULL;
  GtkWidget *radiobutton_____femme;

  MODIFIER = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MODIFIER), _("modifier"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (MODIFIER), fixed14);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_fixed_put (GTK_FIXED (fixed14), fixed15, 0, 0);
  gtk_widget_set_size_request (fixed15, 840, 840);

  entry____id = gtk_entry_new ();
  gtk_widget_show (entry____id);
  gtk_fixed_put (GTK_FIXED (fixed15), entry____id, 112, 64);
  gtk_widget_set_size_request (entry____id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry____id), 8226);

  entry____nom = gtk_entry_new ();
  gtk_widget_show (entry____nom);
  gtk_fixed_put (GTK_FIXED (fixed15), entry____nom, 112, 120);
  gtk_widget_set_size_request (entry____nom, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry____nom), 8226);

  entry____prenom = gtk_entry_new ();
  gtk_widget_show (entry____prenom);
  gtk_fixed_put (GTK_FIXED (fixed15), entry____prenom, 112, 168);
  gtk_widget_set_size_request (entry____prenom, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry____prenom), 8226);

  spinbutton____jour_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 0);
  spinbutton____jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton____jour_adj), 1, 0);
  gtk_widget_show (spinbutton____jour);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton____jour, 208, 360);
  gtk_widget_set_size_request (spinbutton____jour, 60, 27);

  spinbutton__mois_adj = gtk_adjustment_new (0, 1, 31, 1, 10, 0);
  spinbutton__mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton__mois_adj), 1, 0);
  gtk_widget_show (spinbutton__mois);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton__mois, 328, 360);
  gtk_widget_set_size_request (spinbutton__mois, 60, 27);

  spinbutton__annee_adj = gtk_adjustment_new (0, 1990, 2025, 1, 10, 0);
  spinbutton__annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton__annee_adj), 1, 0);
  gtk_widget_show (spinbutton__annee);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton__annee, 464, 360);
  gtk_widget_set_size_request (spinbutton__annee, 60, 27);

  entry____numtelephone = gtk_entry_new ();
  gtk_widget_show (entry____numtelephone);
  gtk_fixed_put (GTK_FIXED (fixed15), entry____numtelephone, 128, 408);
  gtk_widget_set_size_request (entry____numtelephone, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry____numtelephone), 8226);

  entry____addmail = gtk_entry_new ();
  gtk_widget_show (entry____addmail);
  gtk_fixed_put (GTK_FIXED (fixed15), entry____addmail, 120, 520);
  gtk_widget_set_size_request (entry____addmail, 192, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entry____addmail), 8);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry____addmail), 8226);

  spinbutton____sal_adj = gtk_adjustment_new (0, 0, 10000, 1, 10, 0);
  spinbutton____sal = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton____sal_adj), 1, 0);
  gtk_widget_show (spinbutton____sal);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton____sal, 152, 680);
  gtk_widget_set_size_request (spinbutton____sal, 144, 32);

  entry____cin = gtk_entry_new ();
  gtk_widget_show (entry____cin);
  gtk_fixed_put (GTK_FIXED (fixed15), entry____cin, 112, 216);
  gtk_widget_set_size_request (entry____cin, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry____cin), 8226);

  entry____rechercher = gtk_entry_new ();
  gtk_widget_show (entry____rechercher);
  gtk_fixed_put (GTK_FIXED (fixed15), entry____rechercher, 584, 56);
  gtk_widget_set_size_request (entry____rechercher, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry____rechercher), 8226);

  label152 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label152);
  gtk_fixed_put (GTK_FIXED (fixed15), label152, 8, 120);
  gtk_widget_set_size_request (label152, 80, 24);

  label153 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label153);
  gtk_fixed_put (GTK_FIXED (fixed15), label153, 8, 168);
  gtk_widget_set_size_request (label153, 80, 25);

  label154 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label154);
  gtk_fixed_put (GTK_FIXED (fixed15), label154, 24, 216);
  gtk_widget_set_size_request (label154, 56, 25);

  label156 = gtk_label_new (_("Date de naissance :                                    "));
  gtk_widget_show (label156);
  gtk_fixed_put (GTK_FIXED (fixed15), label156, 0, 360);
  gtk_widget_set_size_request (label156, 136, 32);

  label157 = gtk_label_new (_("Telephone : "));
  gtk_widget_show (label157);
  gtk_fixed_put (GTK_FIXED (fixed15), label157, 0, 408);
  gtk_widget_set_size_request (label157, 112, 40);

  label158 = gtk_label_new (_("Gouvernorat :"));
  gtk_widget_show (label158);
  gtk_fixed_put (GTK_FIXED (fixed15), label158, 0, 464);
  gtk_widget_set_size_request (label158, 104, 40);

  label159 = gtk_label_new (_("Mail : "));
  gtk_widget_show (label159);
  gtk_fixed_put (GTK_FIXED (fixed15), label159, 8, 520);
  gtk_widget_set_size_request (label159, 64, 32);

  label160 = gtk_label_new (_("Poste de travail : "));
  gtk_widget_show (label160);
  gtk_fixed_put (GTK_FIXED (fixed15), label160, 0, 568);
  gtk_widget_set_size_request (label160, 144, 48);

  label161 = gtk_label_new (_("ID park : "));
  gtk_widget_show (label161);
  gtk_fixed_put (GTK_FIXED (fixed15), label161, 16, 624);
  gtk_widget_set_size_request (label161, 96, 32);

  label162 = gtk_label_new (_("Salaire :"));
  gtk_widget_show (label162);
  gtk_fixed_put (GTK_FIXED (fixed15), label162, 8, 680);
  gtk_widget_set_size_request (label162, 104, 33);

  button____RECHERCHER_ = gtk_button_new ();
  gtk_widget_show (button____RECHERCHER_);
  gtk_fixed_put (GTK_FIXED (fixed15), button____RECHERCHER_, 440, 56);
  gtk_widget_set_size_request (button____RECHERCHER_, 122, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button____RECHERCHER_), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label163 = gtk_label_new_with_mnemonic (_("Rechercher :"));
  gtk_widget_show (label163);
  gtk_box_pack_start (GTK_BOX (hbox17), label163, FALSE, FALSE, 0);

  button__MODIFIER_ = gtk_button_new ();
  gtk_widget_show (button__MODIFIER_);
  gtk_fixed_put (GTK_FIXED (fixed15), button__MODIFIER_, 560, 752);
  gtk_widget_set_size_request (button__MODIFIER_, 112, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button__MODIFIER_), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label166 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label166);
  gtk_box_pack_start (GTK_BOX (hbox20), label166, FALSE, FALSE, 0);

  button2__retour__mod = gtk_button_new ();
  gtk_widget_show (button2__retour__mod);
  gtk_fixed_put (GTK_FIXED (fixed15), button2__retour__mod, 80, 744);
  gtk_widget_set_size_request (button2__retour__mod, 128, 45);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button2__retour__mod), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label165 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label165);
  gtk_box_pack_start (GTK_BOX (hbox19), label165, FALSE, FALSE, 0);

  label151 = gtk_label_new (_("Id :"));
  gtk_widget_show (label151);
  gtk_fixed_put (GTK_FIXED (fixed15), label151, 32, 72);
  gtk_widget_set_size_request (label151, 41, 17);

  label155 = gtk_label_new (_("sexe : "));
  gtk_widget_show (label155);
  gtk_fixed_put (GTK_FIXED (fixed15), label155, 16, 288);
  gtk_widget_set_size_request (label155, 64, 32);

  comboboxentry____cov = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry____cov);
  gtk_fixed_put (GTK_FIXED (fixed15), comboboxentry____cov, 120, 472);
  gtk_widget_set_size_request (comboboxentry____cov, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("B\303\251ja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Ben Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Sidi Bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Gabes"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Kebili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("M\303\251denine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("La Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____cov), _("Mahdia"));

  checkbutton____maintenence = gtk_check_button_new_with_mnemonic (_("maintenence"));
  gtk_widget_show (checkbutton____maintenence);
  gtk_fixed_put (GTK_FIXED (fixed15), checkbutton____maintenence, 176, 576);
  gtk_widget_set_size_request (checkbutton____maintenence, 118, 24);

  checkbutton____securite = gtk_check_button_new_with_mnemonic (_("securite"));
  gtk_widget_show (checkbutton____securite);
  gtk_fixed_put (GTK_FIXED (fixed15), checkbutton____securite, 320, 576);
  gtk_widget_set_size_request (checkbutton____securite, 118, 24);

  checkbutton____agent = gtk_check_button_new_with_mnemonic (_("agent"));
  gtk_widget_show (checkbutton____agent);
  gtk_fixed_put (GTK_FIXED (fixed15), checkbutton____agent, 448, 576);
  gtk_widget_set_size_request (checkbutton____agent, 118, 24);

  comboboxentry____park = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry____park);
  gtk_fixed_put (GTK_FIXED (fixed15), comboboxentry____park, 152, 624);
  gtk_widget_set_size_request (comboboxentry____park, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____park), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____park), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____park), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry____park), _("4"));

  radiobutton_____homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton_____homme);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton_____homme, 120, 296);
  gtk_widget_set_size_request (radiobutton_____homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_____homme), radiobutton_____homme_group);
  radiobutton_____homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_____homme));

  radiobutton_____femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton_____femme);
  gtk_fixed_put (GTK_FIXED (fixed15), radiobutton_____femme, 288, 296);
  gtk_widget_set_size_request (radiobutton_____femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_____femme), radiobutton_____homme_group);
  radiobutton_____homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_____femme));

  g_signal_connect ((gpointer) button____RECHERCHER_, "clicked",
                    G_CALLBACK (on_button____RECHERCHER__clicked),
                    NULL);
  g_signal_connect ((gpointer) button__MODIFIER_, "clicked",
                    G_CALLBACK (on_button__MODIFIER__clicked),
                    NULL);
  g_signal_connect ((gpointer) button2__retour__mod, "clicked",
                    G_CALLBACK (on_button2__retour__mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_____homme, "toggled",
                    G_CALLBACK (on_radiobutton_____homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_____femme, "toggled",
                    G_CALLBACK (on_radiobutton_____femme_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MODIFIER, MODIFIER, "MODIFIER");
  GLADE_HOOKUP_OBJECT (MODIFIER, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (MODIFIER, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (MODIFIER, entry____id, "entry____id");
  GLADE_HOOKUP_OBJECT (MODIFIER, entry____nom, "entry____nom");
  GLADE_HOOKUP_OBJECT (MODIFIER, entry____prenom, "entry____prenom");
  GLADE_HOOKUP_OBJECT (MODIFIER, spinbutton____jour, "spinbutton____jour");
  GLADE_HOOKUP_OBJECT (MODIFIER, spinbutton__mois, "spinbutton__mois");
  GLADE_HOOKUP_OBJECT (MODIFIER, spinbutton__annee, "spinbutton__annee");
  GLADE_HOOKUP_OBJECT (MODIFIER, entry____numtelephone, "entry____numtelephone");
  GLADE_HOOKUP_OBJECT (MODIFIER, entry____addmail, "entry____addmail");
  GLADE_HOOKUP_OBJECT (MODIFIER, spinbutton____sal, "spinbutton____sal");
  GLADE_HOOKUP_OBJECT (MODIFIER, entry____cin, "entry____cin");
  GLADE_HOOKUP_OBJECT (MODIFIER, entry____rechercher, "entry____rechercher");
  GLADE_HOOKUP_OBJECT (MODIFIER, label152, "label152");
  GLADE_HOOKUP_OBJECT (MODIFIER, label153, "label153");
  GLADE_HOOKUP_OBJECT (MODIFIER, label154, "label154");
  GLADE_HOOKUP_OBJECT (MODIFIER, label156, "label156");
  GLADE_HOOKUP_OBJECT (MODIFIER, label157, "label157");
  GLADE_HOOKUP_OBJECT (MODIFIER, label158, "label158");
  GLADE_HOOKUP_OBJECT (MODIFIER, label159, "label159");
  GLADE_HOOKUP_OBJECT (MODIFIER, label160, "label160");
  GLADE_HOOKUP_OBJECT (MODIFIER, label161, "label161");
  GLADE_HOOKUP_OBJECT (MODIFIER, label162, "label162");
  GLADE_HOOKUP_OBJECT (MODIFIER, button____RECHERCHER_, "button____RECHERCHER_");
  GLADE_HOOKUP_OBJECT (MODIFIER, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (MODIFIER, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (MODIFIER, image17, "image17");
  GLADE_HOOKUP_OBJECT (MODIFIER, label163, "label163");
  GLADE_HOOKUP_OBJECT (MODIFIER, button__MODIFIER_, "button__MODIFIER_");
  GLADE_HOOKUP_OBJECT (MODIFIER, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (MODIFIER, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (MODIFIER, image20, "image20");
  GLADE_HOOKUP_OBJECT (MODIFIER, label166, "label166");
  GLADE_HOOKUP_OBJECT (MODIFIER, button2__retour__mod, "button2__retour__mod");
  GLADE_HOOKUP_OBJECT (MODIFIER, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (MODIFIER, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (MODIFIER, image19, "image19");
  GLADE_HOOKUP_OBJECT (MODIFIER, label165, "label165");
  GLADE_HOOKUP_OBJECT (MODIFIER, label151, "label151");
  GLADE_HOOKUP_OBJECT (MODIFIER, label155, "label155");
  GLADE_HOOKUP_OBJECT (MODIFIER, comboboxentry____cov, "comboboxentry____cov");
  GLADE_HOOKUP_OBJECT (MODIFIER, checkbutton____maintenence, "checkbutton____maintenence");
  GLADE_HOOKUP_OBJECT (MODIFIER, checkbutton____securite, "checkbutton____securite");
  GLADE_HOOKUP_OBJECT (MODIFIER, checkbutton____agent, "checkbutton____agent");
  GLADE_HOOKUP_OBJECT (MODIFIER, comboboxentry____park, "comboboxentry____park");
  GLADE_HOOKUP_OBJECT (MODIFIER, radiobutton_____homme, "radiobutton_____homme");
  GLADE_HOOKUP_OBJECT (MODIFIER, radiobutton_____femme, "radiobutton_____femme");

  return MODIFIER;
}

GtkWidget*
create_SUPPRIMER (void)
{
  GtkWidget *SUPPRIMER;
  GtkWidget *fixed16;
  GtkWidget *buttonsearch;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label167;
  GtkWidget *searchid;
  GtkWidget *treeviewwe2;
  GtkWidget *buttonsup;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label168;
  GtkWidget *button3retouur;

  SUPPRIMER = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (SUPPRIMER), _("supprimer "));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (SUPPRIMER), fixed16);

  buttonsearch = gtk_button_new ();
  gtk_widget_show (buttonsearch);
  gtk_fixed_put (GTK_FIXED (fixed16), buttonsearch, 432, 40);
  gtk_widget_set_size_request (buttonsearch, 144, 29);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonsearch), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label167 = gtk_label_new_with_mnemonic (_("search"));
  gtk_widget_show (label167);
  gtk_box_pack_start (GTK_BOX (hbox21), label167, FALSE, FALSE, 0);

  searchid = gtk_entry_new ();
  gtk_widget_show (searchid);
  gtk_fixed_put (GTK_FIXED (fixed16), searchid, 600, 40);
  gtk_widget_set_size_request (searchid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (searchid), 8226);

  treeviewwe2 = gtk_tree_view_new ();
  gtk_widget_show (treeviewwe2);
  gtk_fixed_put (GTK_FIXED (fixed16), treeviewwe2, 0, 136);
  gtk_widget_set_size_request (treeviewwe2, 848, 240);

  buttonsup = gtk_button_new ();
  gtk_widget_show (buttonsup);
  gtk_fixed_put (GTK_FIXED (fixed16), buttonsup, 616, 424);
  gtk_widget_set_size_request (buttonsup, 168, 45);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (buttonsup), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label168 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label168);
  gtk_box_pack_start (GTK_BOX (hbox22), label168, FALSE, FALSE, 0);

  button3retouur = gtk_button_new_with_mnemonic (_("retouur"));
  gtk_widget_show (button3retouur);
  gtk_fixed_put (GTK_FIXED (fixed16), button3retouur, 48, 424);
  gtk_widget_set_size_request (button3retouur, 152, 45);

  g_signal_connect ((gpointer) buttonsearch, "clicked",
                    G_CALLBACK (on_buttonsearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsup, "clicked",
                    G_CALLBACK (on_buttonsup_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3retouur, "clicked",
                    G_CALLBACK (on_button3retouur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (SUPPRIMER, SUPPRIMER, "SUPPRIMER");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, buttonsearch, "buttonsearch");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, image21, "image21");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, label167, "label167");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, searchid, "searchid");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, treeviewwe2, "treeviewwe2");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, buttonsup, "buttonsup");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, image22, "image22");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, label168, "label168");
  GLADE_HOOKUP_OBJECT (SUPPRIMER, button3retouur, "button3retouur");

  return SUPPRIMER;
}

GtkWidget*
create_LISTEAGENT (void)
{
  GtkWidget *LISTEAGENT;
  GtkWidget *fixed17;
  GtkWidget *treeview2;
  GtkWidget *buttonretourlistes;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label171;
  GtkWidget *afficherlesagents;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label170;

  LISTEAGENT = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (LISTEAGENT), _("listeagent"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (LISTEAGENT), fixed17);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed17), treeview2, 16, 96);
  gtk_widget_set_size_request (treeview2, 1024, 344);

  buttonretourlistes = gtk_button_new ();
  gtk_widget_show (buttonretourlistes);
  gtk_fixed_put (GTK_FIXED (fixed17), buttonretourlistes, 176, 456);
  gtk_widget_set_size_request (buttonretourlistes, 120, 37);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (buttonretourlistes), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label171 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label171);
  gtk_box_pack_start (GTK_BOX (hbox25), label171, FALSE, FALSE, 0);

  afficherlesagents = gtk_button_new ();
  gtk_widget_show (afficherlesagents);
  gtk_fixed_put (GTK_FIXED (fixed17), afficherlesagents, 352, 32);
  gtk_widget_set_size_request (afficherlesagents, 320, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (afficherlesagents), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label170 = gtk_label_new_with_mnemonic (_("LISTE AGENTS "));
  gtk_widget_show (label170);
  gtk_box_pack_start (GTK_BOX (hbox24), label170, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonretourlistes, "clicked",
                    G_CALLBACK (on_buttonretourlistes_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficherlesagents, "clicked",
                    G_CALLBACK (on_afficherlesagents_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LISTEAGENT, LISTEAGENT, "LISTEAGENT");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, buttonretourlistes, "buttonretourlistes");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, image25, "image25");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, label171, "label171");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, afficherlesagents, "afficherlesagents");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, image24, "image24");
  GLADE_HOOKUP_OBJECT (LISTEAGENT, label170, "label170");

  return LISTEAGENT;
}

