/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_AJOUTER (void);
GtkWidget* create_window1 (void);
GtkWidget* create_HOME (void);
GtkWidget* create_MODIFIER (void);
GtkWidget* create_SUPPRIMER (void);
GtkWidget* create_LISTEAGENT (void);
